### ISSUE TITLE
vaex.open : not able to open file 

### ISSUE THREAD

**Issue by ghost** [vaexio/vaex-talks#9]
1- vaex_df = vaex.from_pandas(cap_file, copy_index=False)
2 - print (vaex_df)
3 - vaex_df.export_hdf5(path='/Users/p0p029i/Downloads/cap_monthly_20210625_2.hdf5', progress=True)
4 - df = vaex.open('/Users/p0p029i/Downloads/cap_monthly_20210625_2.hdf5')

above top three lines are working fine but, when i am executing 4th line, it is not working. I have checked my download folder also, file _cap_monthly_20210625_2.hdf5_ has been created also.

Error which line 4 is giving:

ERROR:MainThread:vaex:error opening '/Users/p0p029i/Downloads/cap_monthly_20210625_2.hdf5'
Traceback (most recent call last):
  File "/Users/p0p029i/PycharmProjects/datavalidation/main.py", line 85, in <module>
    df = vaex.open('/Users/p0p029i/Downloads/cap_monthly_20210625_2.hdf5')
  File "/Users/p0p029i/PycharmProjects/datavalidation/venv/lib/python3.9/site-packages/vaex/__init__.py", line 223, in open
    ds = vaex.dataset.open(path, fs_options=fs_options, fs=fs, **kwargs)
  File "/Users/p0p029i/PycharmProjects/datavalidation/venv/lib/python3.9/site-packages/vaex/dataset.py", line 70, in open
    return opener.open(path, fs_options=fs_options, fs=fs, *args, **kwargs)
  File "/Users/p0p029i/PycharmProjects/datavalidation/venv/lib/python3.9/site-packages/vaex/dataset.py", line 1447, in open
    return cls(path, *args, **kwargs)
  File "/Users/p0p029i/PycharmProjects/datavalidation/venv/lib/python3.9/site-packages/vaex/hdf5/dataset.py", line 71, in __init__
    self._load()
  File "/Users/p0p029i/PycharmProjects/datavalidation/venv/lib/python3.9/site-packages/vaex/hdf5/dataset.py", line 194, in _load
    self._load_columns(self.h5file["/table"])
  File "/Users/p0p029i/PycharmProjects/datavalidation/venv/lib/python3.9/site-packages/vaex/hdf5/dataset.py", line 337, in _load_columns
    data = column if self._version == 1 else column['data']
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/p0p029i/PycharmProjects/datavalidation/venv/lib/python3.9/site-packages/h5py/_hl/group.py", line 305, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
**KeyError: "Unable to open object (object 'data' doesn't exist)"**

**Comment by JovanVeljanoski** [comment]
Can you tell us which version of vaex you are using. 

Also - this may be a long shot - can you try the same but not using pycharm? Maybe use a console or something.

**Comment by ghost** [comment]
Hi Jovan,

Thanks for your quick response. I am using version 4.3

I will try to it on console. Will let you know

**Comment by ghost** [comment]
Hi Jovan,

I tried using console also. but getting the same error.
<img width="813" alt="Screen Shot 2021-06-29 at 4 21 30 PM" src="https://user-images.githubusercontent.com/21122053/123785573-4f5d4880-d8f6-11eb-99fe-1fb1038cbd3e.png">

**Comment by JovanVeljanoski** [comment]
Hm.. that is a bit strange..

Can you please tell us what version of pyarrow and h5py you have installed. 
Also - for sanity checks can you do something like

```
import vaex
df = vaex.example()
df.export('tmp.hdf5')
df2  = vaex.open('tmp.hdf5')
df2
```

If this codeblock works, can you give us some description of the data. Do you have columns that contain lists or dicts and stuff like that (although that is unlikely to be the cause given the error message).

**Comment by ghost** [comment]
pyarrow and h5py  - 4.0.1  and 3.3.0 respectively. I ran the code but getting an error. Actually regarding my file it is excel file  and donot contain any dictionaries, also  as i a mentioned in my previous post, that i am able to create dataframe using **vaex.from_pandas** and also able to save file in hdf5 foramt. 

**Ran the code** 
import vaex
df = vaex.example()
df.export('tmp.hdf5')
df2  = vaex.open('tmp.hdf5')
df2


**Error -**
/Users/p0p029i/PycharmProjects/datavalidation/venv/bin/python /Users/p0p029i/PycharmProjects/datavalidation/main.py
Downloading https://github.com/vaexio/vaex-datasets/releases/download/v1.0/helmi-dezeeuw-2000-FeH-v2-10percent.hdf5 to /Users/p0p029i/.vaex/data/helmi-dezeeuw-2000-FeH-v2-10percent.hdf5
wget failed, using urlretrieve
sh: wget: command not found
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1257, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1303, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1252, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1012, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 952, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1426, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/p0p029i/PycharmProjects/datavalidation/main.py", line 96, in <module>
    df = vaex.example()
  File "/Users/p0p029i/PycharmProjects/datavalidation/venv/lib/python3.9/site-packages/vaex/__init__.py", line 585, in example
    return vaex.datasets.helmi_de_zeeuw_10percent.fetch()
  File "/Users/p0p029i/PycharmProjects/datavalidation/venv/lib/python3.9/site-packages/vaex/datasets.py", line 47, in fetch
    self.download(force=force_download)
  File "/Users/p0p029i/PycharmProjects/datavalidation/venv/lib/python3.9/site-packages/vaex/datasets.py", line 41, in download
    self.download_urlretrieve()
  File "/Users/p0p029i/PycharmProjects/datavalidation/venv/lib/python3.9/site-packages/vaex/datasets.py", line 44, in download_urlretrieve
    urlretrieve(self.url, self.filename)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>

**Comment by JovanVeljanoski** [comment]
Ok, so the error you are getting for the code snippet i suggested is something else entirely - you seem to have a problem downloading the example dataset. 

Anyway, if possible, can you install/downgrade h2py to version 2.10.0? Then you can either try with your data, or perhaps better (for debugging purposes) to try this modified example of above (avoids the download of the example dataset):

```python
import vaex
df = vaex.from_arrays(x=[1, 2], y=[-10, 10])
df.export('tmp.hdf5')
df2  = vaex.open('tmp.hdf5')
df2
```

**Comment by ghost** [comment]
Hi Jovan,

Yes the code worked. I downgraded h5py to 3.2 .  So what should be my next step. Should i try to run the code on 3.2 version of h5py ?

**Comment by ghost** [comment]
I downgraded to 3.2 because for 2.10 it was giving me error

**Comment by JovanVeljanoski** [comment]
ok, so If i understand correctly, h5py 3.3.0 causes problems, but 3.2 works ok?

**Comment by ghost** [comment]
So should i try with 3.2 ?

**Comment by JovanVeljanoski** [comment]
If h5py version 3.2 works for you, just keep using that :).

**Comment by ghost** [comment]
Ok Jovan. Thanks for the help.  :) Really appreciate it

**Comment by ghost** [comment]
Closing the loop
